### ISSUE TITLE
When uploading multiple files only first file is indexed.

### ISSUE THREAD

**Issue by PrintsCharming** [akshata29/chatpdf#16] opened 2023-05-05 06:22 UTC
It appears that when uploading multiple files using Cognitive Services only the first file is indexed. All of the uploaded files successfully make it into the chatpdf container but the index only contains references to the first document.

**Comment by akshata29** [comment] 2023-05-06 00:09
Thank you.  Fixed the issue, looks like it could still be applicable to all store, and the issue is tied to metadata can't have "-" (underscore).  So assuming you had a file (possibly first one?) and with default name of the name of the first file as index and it setting that as index Name was causing the issue.

Closing the issue, let me know if you still run into that.

**Closed by akshata29** 2023-05-06 00:09 UTC
